dist: trusty
language: node_js
node_js:
  - "0.10"
before_install:
install:
  - npm install
# script:
#  - npm test
notifications:
  email: false
  slack:
    rooms:
    - kedia:yBh1h5UbplmejFa7vTou1MD0#xdv